# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
